### ISSUE TITLE
[ERROR]: Eccezione non gestita!

### ISSUE THREAD

**Issue by wes1993** [fabifont/abb-bot#11]
Ciao!!!
Grazie mille per l'ottimo lavoro!!! 
sto provando a farlo funzionare ma ricevo l'errore in oggetto.
Ti allego il log completo:
```
[INFO]: Logging su file abilitato: C:\Users\stefa\aliexpress\logfile.txt
[INFO]: Caricamento della configurazione in corso...
[INFO]: Configurazione caricata correttamente
[INFO]: Chiudo le istanze di Chrome e ChromeDriver
[INFO]: TenMinuteMailNet ha ratio 1,000000
[INFO]: Provider scelto => TenMinuteMailNet
[INFO]: Letta email temporanea!
[INFO]: Letto codice di verifica di Twitter: 288367
[INFO]: Creato account Twitter!
[INFO]: TenMinuteMailNet ha avuto successo
[ERROR]: Eccezione non gestita!
[TRACE]: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for com.fabifont.aliexpress.account.Account$$Lambda$429/0x0000000800d8f2b0@3e52c3b2 (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'PC-STUDIO', ip: '169.254.199.75', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.150, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: C:\Users\stefa\aliexpress\c...}, goog:chromeOptions: {debuggerAddress: localhost:59573}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 71f5bd3ce743b28f6f276ad1ab139fad
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:211)
	at com.fabifont.aliexpress.account.Account.clickAliexpress(Account.java:185)
	at com.fabifont.aliexpress.account.AccountWorker.call(AccountWorker.java:58)
	at com.fabifont.aliexpress.account.AccountWorker.call(AccountWorker.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[INFO]: --------------------
[INFO]: 0 click con successo
[INFO]: 1 errori
[INFO]: 0 ban di IP
[INFO]: --------------------
[INFO]: Chiudo le istanze di Chrome e ChromeDriver
[INFO]: TenMinuteMailNet ha ratio 1,000000
[INFO]: Provider scelto => TenMinuteMailNet
[INFO]: Letta email temporanea!
[INFO]: Letto codice di verifica di Twitter: 684533
[INFO]: Creato account Twitter!
[INFO]: TenMinuteMailNet ha avuto successo
[ERROR]: Eccezione non gestita!
[TRACE]: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for com.fabifont.aliexpress.account.Account$$Lambda$429/0x0000000800d8f2b0@27429d1d (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'PC-STUDIO', ip: '169.254.199.75', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.150, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: C:\Users\stefa\aliexpress\c...}, goog:chromeOptions: {debuggerAddress: localhost:59685}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 7ce4b52ca951cd5479cbeaab86dd6051
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:211)
	at com.fabifont.aliexpress.account.Account.clickAliexpress(Account.java:185)
	at com.fabifont.aliexpress.account.AccountWorker.call(AccountWorker.java:58)
	at com.fabifont.aliexpress.account.AccountWorker.call(AccountWorker.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[INFO]: --------------------
[INFO]: 0 click con successo
[INFO]: 2 errori
[INFO]: 0 ban di IP
[INFO]: --------------------
[INFO]: Chiudo le istanze di Chrome e ChromeDriver
[INFO]: TenMinuteMailNet ha ratio 1,000000
[INFO]: Provider scelto => TenMinuteMailNet
[INFO]: Letta email temporanea!
[INFO]: Letto codice di verifica di Twitter: 018326
[INFO]: Creato account Twitter!
[INFO]: TenMinuteMailNet ha avuto successo
[ERROR]: Eccezione non gestita!
[TRACE]: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for com.fabifont.aliexpress.account.Account$$Lambda$429/0x0000000800d8f2b0@50592c18 (tried for 60 second(s) with 500 milliseconds interval)
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'PC-STUDIO', ip: '169.254.199.75', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.150, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: C:\Users\stefa\aliexpress\c...}, goog:chromeOptions: {debuggerAddress: localhost:49818}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 21a31772a3db27a82a8762ba53366b2a
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:211)
	at com.fabifont.aliexpress.account.Account.clickAliexpress(Account.java:185)
	at com.fabifont.aliexpress.account.AccountWorker.call(AccountWorker.java:58)
	at com.fabifont.aliexpress.account.AccountWorker.call(AccountWorker.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
Grazie mille
Stefano

**Comment by fabifont** [comment]
@wes1993 A che punto si blocca? Dopo la creazione dell'account?

**Comment by wes1993** [comment]
Grazie mille per la risposta,
No crea account Twitter e torna su AliExpress e a quel punto si blocca.
Se dal browser provo a cliccare a mano mi dice la richiesta non può essere eseguita per motivi di sicurezza

**Comment by fabifont** [comment]
@wes1993 Ok, praticamente a quel punto l'account di AliExpress è già stato creato. Devi solo cambiare il redirect e i vari xpath per cliccare sulla busta. Per l'errore di sicurezza probabilmente è necessario usare i DNS di Google oppure prendere un endpoint di AliExpress diverso da quello corrente. Purtroppo io ho abbandonato il progetto per mancanza di tempo. Però chiunque può contribuire e inviare delle pull requests.

**Comment by wes1993** [comment]
Ok allora proverò a studiare bene la cosa :)

**Comment by Reefoldfiveteen** [comment]
> Grazie mille per la risposta,
> No crea account Twitter e torna su AliExpress e a quel punto si blocca.
> Se dal browser provo a cliccare a mano mi dice la richiesta non può essere eseguita per motivi di sicurezza

Hy @wes1993 , Did you find a solution to avoid security reasons? I also encountered that after entering the credit card, so the voucher could not be claimed for security reasons,
or can only use 2x the opportunity for the same credit card even though it has been deleted from the previous account?

Google translated>
ciao @wes1993, hai trovato una soluzione per evitare motivi di sicurezza? Ho anche riscontrato che dopo aver inserito la carta di credito, quindi il voucher non può essere richiesto per motivi di sicurezza,
o puoi usare solo 2x l'opportunità per la stessa carta di credito anche se è stata cancellata dall'account precedente?

**Comment by wes1993** [comment]
Sorry... I don’t have find a solution... unfortunately I don’t have time to search... but if you found a solution please send here a message :)

**Comment by Reefoldfiveteen** [comment]
@wes1993 ok, thanks for your answer,, :)

**Comment by eguuuu** [comment]
> Sorry... I don’t have find a solution... unfortunately I don’t have time to search... but if you found a solution please send here a message :)

Can you run this project perfectly
