### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Ananas0631** [fabifont/abb-bot#8]
Im sorry for disturbing you again,
but I have 2 problems I think

1-Is that normal?
https://hizliresim.com/WbWavC

2-How much time I must wait?

3-Im so sorry for my ignorance,and I get this error I suppose:
ChromeDriver was started successfully.
ChromeDriver was started successfully.
[ERROR]: Eccezione non gestita!
[TRACE]: org.openqa.selenium.SessionNotCreatedException: session not created: Th
is version of ChromeDriver only supports Chrome version 88
Current browser version is 87.0.4280.141 with binary path C:\Program Files\Googl
e\Chrome\Application\chrome.exe
Build info: version: '4.0.0-alpha-7', revision: 'de8579b6d5'
System info: host: 'DESKTOP-0HK0F90', ip: '192.168.42.253', os.name: 'Windows 10
', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.9.1'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
        GetHandleVerifier [0x008DB963+483]
        GetHandleVerifier [0x008DB941+449]
        GetHandleVerifier [0x00C83308+3832712]
        GetHandleVerifier [0x00C9D69A+3940122]
        GetHandleVerifier [0x00C99AFB+3924859]
        GetHandleVerifier [0x00C97D9C+3917340]
        GetHandleVerifier [0x00CBE7FE+4075646]
        GetHandleVerifier [0x00CBE56C+4074988]
        GetHandleVerifier [0x00CBB2EB+4062059]
        GetHandleVerifier [0x00C9ED14+3945876]
        GetHandleVerifier [0x00C9FBCE+3949646]
        GetHandleVerifier [0x00C9FB59+3949529]
        Ordinal0 [0x0089B5CC+46540]
        Ordinal0 [0x00899F53+40787]
        Ordinal0 [0x00899B12+39698]
        GetHandleVerifier [0x00BA1468+2907368]
        GetHandleVerifier [0x009E71EE+1096302]
        GetHandleVerifier [0x009A3E8D+821005]
        GetHandleVerifier [0x009A396B+819691]
        GetHandleVerifier [0x009A3881+819457]
        GetHandleVerifier [0x009CF463+998627]
        BaseThreadInitThunk [0x75C0FA29+25]
        RtlGetAppContainerNamedObjectPath [0x778D75F4+228]
        RtlGetAppContainerNamedObjectPath [0x778D75C4+180]

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInsta
nce0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInsta
nce(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newI
nstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:
490)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0
(W3CHandshakeResponse.java:62)
        at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFuncti
on$0(HandshakeResponse.java:30)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$1(P
rotocolHandshake.java:126)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipe
line.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Splitera
tors.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Refere
ncePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Abstra
ctPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline
.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractP
ipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.
java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline
.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipel
ine.java:543)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHa
ndshake.java:128)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHa
ndshake.java:75)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExe
cutor.java:139)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(Driv
erCommandExecutor.java:123)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.ja
va:501)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriv
er.java:207)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.jav
a:127)
        at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.jav
a:93)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:163)

        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:150)

        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)

        at com.fabifont.aliexpress.account.AccountWorker.call(AccountWorker.java
:50)
        at com.fabifont.aliexpress.account.AccountWorker.call(AccountWorker.java
:17)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo
lExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo
olExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

[INFO]: --------------------
![Ekran Görüntüsü (12)](https://user-images.githubusercontent.com/77831170/105611865-0219ff80-5dc9-11eb-89ba-72b1de2aa1a3.png)

**Comment by fabifont** [comment]
@Ananas0631 You must update chrome to version 88.

The bot also needs an update to complete the click routine.

I don't have time to do that. The bot is open source so anyone can contribute.

If you are not a developer and you can't understand / fix the bot please quit the project.

**Comment by Ananas0631** [comment]
Ok,thanks 

I am not a devolper,its my last question,
Can't I get even one click if I will update chrome 88 with this version?

**Comment by fabifont** [comment]
@Ananas0631 No, the bot also needs an update.
